# Generated by Django 4.2.30 on 2026-09-16 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estetica_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaPaquete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_sesiones', models.IntegerField(default=1)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estetica_regla_paquete',
            },
        ),
        migrations.CreateModel(
            name='BilleteraCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sesiones_totales', models.IntegerField()),
                ('sesiones_restantes', models.IntegerField()),
                ('fecha_compra', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billeteras', to='estetica_servicios.servicioestetica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_comprados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estetica_billetera_cliente',
            },
        ),
    ]
