# Generated by Django 4.2.30 on 2026-08-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionGlobal',
        ),
        migrations.RemoveField(
            model_name='resena',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='notas_medicas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.DeleteModel(
            name='Recurrencia',
        ),
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
