# Generated by Django 4.2.30 on 2026-09-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_configuracionglobal_remove_resena_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cupo_actual',
            field=models.IntegerField(default=0),
        ),
    ]
