# Generated by Django 4.2.30 on 2026-09-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_turno_cupo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
