# Generated by Django 4.2.30 on 2026-08-11 00:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=60)),
                ('cupo_maximo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupo_minimo', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clases',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cupo_maximo_defecto', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('cupo_minimo_defecto', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('horas_limite_cancelacion', models.IntegerField(default=24)),
                ('horas_evaluacion_automatica', models.IntegerField(default=25)),
                ('dias_vencimiento_plan', models.IntegerField(default=30)),
                ('dias_alerta_vencimiento', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
                'db_table': 'configuracion_global',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_clases', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'planes',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_index=True)),
                ('hora_inicio', models.TimeField(db_index=True)),
                ('hora_fin', models.TimeField()),
                ('cupo_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], db_index=True, default='PROGRAMADO', max_length=20)),
                ('evaluado_25hs', models.BooleanField(db_index=True, default=False)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='core.clase')),
            ],
            options={
                'db_table': 'turnos',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clases_restantes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], db_index=True, default='ACTIVO', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='suscripciones', to='core.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suscripciones',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_recurrente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA_TIEMPO', 'Cancelada a Tiempo'), ('CANCELADA_TARDIA', 'Cancelada Tardía'), ('TOMADA', 'Tomada')], db_index=True, default='CONFIRMADA', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='core.suscripcion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.turno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
        migrations.CreateModel(
            name='Recurrencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrencias', to='core.clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurrencias',
            },
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'hora_inicio'], name='idx_turnos_fecha_hora'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('fecha', 'hora_inicio', 'clase'), name='unique_turno'),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.CheckConstraint(check=models.Q(('cupo_actual__gte', 0)), name='check_cupo_minimo'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario', 'estado'], name='idx_reservas_usuario_estado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('turno', 'usuario'), name='unique_reserva_usuario'),
        ),
        migrations.AddConstraint(
            model_name='recurrencia',
            constraint=models.UniqueConstraint(fields=('clase', 'dia_semana', 'hora_inicio', 'usuario'), name='unique_recurrencia'),
        ),
    ]
