# Generated by Django 4.2.30 on 2026-08-22 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('color_identificador', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profesores',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notas_medicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA_TIEMPO', 'Cancelada a Tiempo'), ('CANCELADA_TARDIA', 'Cancelada Tardía'), ('TOMADA', 'Tomada'), ('AUSENTE', 'Ausente')], db_index=True, default='CONFIRMADA', max_length=30),
        ),
        migrations.AddField(
            model_name='turno',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='core.profesor'),
        ),
    ]
