# Generated by Django 4.2.30 on 2026-08-23 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profesor_usuario_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurrencia',
            name='unique_recurrencia',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_reserva_usuario',
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='unique_turno',
        ),
        migrations.RemoveConstraint(
            model_name='turno',
            name='check_cupo_minimo',
        ),
        migrations.RemoveIndex(
            model_name='reserva',
            name='idx_reservas_usuario_estado',
        ),
        migrations.RemoveIndex(
            model_name='turno',
            name='idx_turnos_fecha_hora',
        ),
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurrencia',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo_maximo',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo_minimo',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='cupo_maximo_defecto',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='cupo_minimo_defecto',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='horas_limite_cancelacion',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='configuracionglobal',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clase'),
        ),
        migrations.AlterField(
            model_name='recurrencia',
            name='dia_semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='suscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_asociadas', to='core.suscripcion'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='clases_restantes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='cupo_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='evaluado_25hs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROFESOR', 'Profesor'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('turno', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='turno',
            index=models.Index(fields=['fecha', 'estado'], name='turnos_fecha_0ac2ea_idx'),
        ),
    ]
