# Generated by Django 4.2.30 on 2026-08-24 01:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_recurrencia_unique_recurrencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='core.clase')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas', to='core.profesor')),
            ],
            options={
                'db_table': 'plantillas_turno',
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_generados', to='core.plantillaturno'),
        ),
    ]
