# Generated by Django 4.2.30 on 2026-08-25 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profesor_fecha_nacimiento_profesor_sexo_usuario_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resena',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
