# Generated by Django 4.2.30 on 2026-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_acreditacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CONCILIADA', 'Conciliada'), ('IGNORADA', 'Ignorada')], default='DISPONIBLE', max_length=20)),
                ('datos_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
