# Generated by Django 4.2.30 on 2026-08-28 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('color_identificador', models.CharField(default='#3B82F6', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor_plugin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plugin_profesores',
            },
        ),
        migrations.CreateModel(
            name='TurnoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_asignado', to='core.turno')),
            ],
            options={
                'db_table': 'plugin_turnos_profesores',
            },
        ),
        migrations.CreateModel(
            name='PlantillaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantilla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor_asignado', to='core.plantillaturno')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesores.profesor')),
            ],
            options={
                'db_table': 'plugin_plantillas_profesores',
            },
        ),
    ]
