server {
    listen 80;
    server_name localhost;

    # 1. Redirección de la raíz a estética
    location = / {
        return 302 /estetica;
    }

    # 2. Servir los archivos estáticos compilados de la vidriera (React/Vite)
    location / {
        root /var/www/landings;
        index index.html;
        # Esto permite que React Router maneje las rutas (ej. /estetica, /pilates) sin dar error 404
        try_files $uri $uri/ /index.html;
    }
}
