# Generated by Django 4.2.30 on 2026-09-16 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estetica_servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('break_inicio', models.TimeField(blank=True, null=True)),
                ('break_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estetica_disponibilidad_dia',
            },
        ),
        migrations.CreateModel(
            name='ReservaEstetica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('ASISTIO', 'Asistió'), ('NO_ASISTIO', 'No Asistió')], default='CONFIRMADA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_agendadas', to='estetica_servicios.servicioestetica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_estetica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'estetica_reserva',
            },
        ),
    ]
