# Generated by Django 4.2.30 on 2026-08-28 13:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_clases', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plugin_planes',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('clases_restantes', models.IntegerField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('AGOTADO', 'Agotado'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membresias.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plugin_suscripciones',
            },
        ),
        migrations.CreateModel(
            name='ReservaMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumo_suscripcion', to='core.reserva')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membresias.suscripcion')),
            ],
            options={
                'db_table': 'plugin_reservas_membresias',
            },
        ),
    ]
